namespace BCDemoAI;

// Codeunit for purchase order approval business logic
// Generated by Claude Code, manually added: permission check, GDPR DataClassification, pending check
codeunit 50200 "ZZ Purchase Approval Mgmt"
{
    // Approval limit — will move to Setup table in v2
    var
        ApprovalLimit: Decimal;

    trigger OnRun()
    begin
        ApprovalLimit := 50000;
    end;

    // Requests approval for a purchase order
    procedure RequestApproval(var PurchHeader: Record "Purchase Header")
    var
        ApprovalEntry: Record "ZZ Purchase Approval Entry";
        ApprovalEmail: Codeunit "ZZ Purchase Approval Email";
    begin
        // Validate — only for purchase orders
        PurchHeader.TestField("Document Type", PurchHeader."Document Type"::Order);

        // Check if order exceeds limit
        if PurchHeader."Amount Including VAT" <= ApprovalLimit then
            exit;

        // Check if there is already a pending request (manually added — AI missed this)
        ApprovalEntry.SetRange("Purchase Order No.", PurchHeader."No.");
        ApprovalEntry.SetRange(Status, ApprovalEntry.Status::Pending);
        if not ApprovalEntry.IsEmpty() then
            Error('An open approval request already exists for this order.');

        // Create approval request entry
        ApprovalEntry.Init();
        ApprovalEntry."Purchase Order No." := PurchHeader."No.";
        ApprovalEntry."Order Amount" := PurchHeader."Amount Including VAT";
        ApprovalEntry.Status := ApprovalEntry.Status::Pending;
        ApprovalEntry."Requester User ID" := UserId();
        ApprovalEntry."Request Date Time" := CurrentDateTime();
        ApprovalEntry."Approver User ID" := GetDefaultApprover();
        ApprovalEntry.Insert(true);

        // Send email notification
        ApprovalEmail.SendApprovalRequest(ApprovalEntry);

        Message('Approval request has been sent to the purchasing manager.');
    end;

    // Approves a purchase order
    procedure ApproveOrder(ApprovalEntryNo: Integer)
    var
        ApprovalEntry: Record "ZZ Purchase Approval Entry";
    begin
        ApprovalEntry.Get(ApprovalEntryNo);

        if ApprovalEntry.Status <> ApprovalEntry.Status::Pending then
            Error('This request has already been processed (status: %1).', ApprovalEntry.Status);

        // Permission check — added manually after AI code review
        if ApprovalEntry."Approver User ID" <> UserId() then
            Error('You do not have permission to approve this request.');

        ApprovalEntry.Status := ApprovalEntry.Status::Approved;
        ApprovalEntry."Decision Date Time" := CurrentDateTime();
        ApprovalEntry.Modify(true);

        Message('Order %1 has been approved.', ApprovalEntry."Purchase Order No.");
    end;

    // Rejects a purchase order
    procedure RejectOrder(ApprovalEntryNo: Integer; Comment: Text[250])
    var
        ApprovalEntry: Record "ZZ Purchase Approval Entry";
        ApprovalEmail: Codeunit "ZZ Purchase Approval Email";
    begin
        ApprovalEntry.Get(ApprovalEntryNo);

        if ApprovalEntry.Status <> ApprovalEntry.Status::Pending then
            Error('This request has already been processed (status: %1).', ApprovalEntry.Status);

        if ApprovalEntry."Approver User ID" <> UserId() then
            Error('You do not have permission to reject this request.');

        // Comment is mandatory on rejection
        if Comment = '' then
            Error('You must provide a reason when rejecting.');

        ApprovalEntry.Status := ApprovalEntry.Status::Rejected;
        ApprovalEntry."Rejection Comment" := Comment;
        ApprovalEntry."Decision Date Time" := CurrentDateTime();
        ApprovalEntry.Modify(true);

        // Notify the requester
        ApprovalEmail.SendRejectionNotification(ApprovalEntry);

        Message('Order %1 has been rejected.', ApprovalEntry."Purchase Order No.");
    end;

    // Returns the default approver — placeholder for demo
    local procedure GetDefaultApprover(): Code[50]
    begin
        // TODO v2: Read from ZZ Purchase Approval Setup table
        exit('ADMIN');
    end;
}
