namespace BCDemoAI;

// Codeunit for email notifications in the approval process
// Generated by Claude Code, fixed: using Email codeunit instead of SMTP Management (BC v27)
codeunit 50201 "ZZ Purchase Approval Email"
{
    // Sends email notification to the approver
    procedure SendApprovalRequest(ApprovalEntry: Record "ZZ Purchase Approval Entry")
    var
        PurchHeader: Record "Purchase Header";
        EmailMessage: Codeunit "Email Message";
        Email: Codeunit Email;
        Recipients: List of [Text];
        Subject: Text;
        Body: Text;
    begin
        if not PurchHeader.Get(PurchHeader."Document Type"::Order, ApprovalEntry."Purchase Order No.") then
            exit;

        Recipients.Add(GetUserEmail(ApprovalEntry."Approver User ID"));
        if Recipients.Count = 0 then
            exit; // No email — skip notification

        Subject := StrSubstNo('Approval request for order %1', ApprovalEntry."Purchase Order No.");

        Body := StrSubstNo(
            '<p>Hello,</p>' +
            '<p>Requester <b>%1</b> requests approval for purchase order no. <b>%2</b>.</p>' +
            '<p>Vendor: %3<br/>Total amount: %4</p>' +
            '<p>To approve or reject, go to Business Central → Purchase Approval Entries.</p>',
            ApprovalEntry."Requester User ID",
            ApprovalEntry."Purchase Order No.",
            PurchHeader."Buy-from Vendor Name",
            Format(ApprovalEntry."Order Amount", 0, '<Integer Thousand><Decimals,2>')
        );

        EmailMessage.Create(Recipients, Subject, Body, true);
        Email.Send(EmailMessage);
    end;

    // Sends rejection notification to the requester
    procedure SendRejectionNotification(ApprovalEntry: Record "ZZ Purchase Approval Entry")
    var
        EmailMessage: Codeunit "Email Message";
        Email: Codeunit Email;
        Recipients: List of [Text];
        Subject: Text;
        Body: Text;
    begin
        Recipients.Add(GetUserEmail(ApprovalEntry."Requester User ID"));
        if Recipients.Count = 0 then
            exit;

        Subject := StrSubstNo('Order %1 has been rejected', ApprovalEntry."Purchase Order No.");

        Body := StrSubstNo(
            '<p>Hello,</p>' +
            '<p>Your approval request for order no. <b>%1</b> has been <b>rejected</b>.</p>' +
            '<p>Reason: %2</p>' +
            '<p>Contact the purchasing manager for more information.</p>',
            ApprovalEntry."Purchase Order No.",
            ApprovalEntry."Rejection Comment"
        );

        EmailMessage.Create(Recipients, Subject, Body, true);
        Email.Send(EmailMessage);
    end;

    // Reads the user's email address
    local procedure GetUserEmail(UserID: Code[50]): Text
    var
        UserRecord: Record User;
    begin
        if UserRecord.Get(UserID) then
            exit(UserRecord."Contact Email");
        exit('');
    end;
}
